apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-info-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-info-service
  template:
    metadata:
      labels:
        app: customer-info-service
    spec:
      containers:
        - name: customer-info-service
          image: ghcr.io/sutarps/customer-info:latest
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
          readinessProbe:
            httpGet:
                path: /heathz
                port: 8080
                scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3


