apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-info-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-info-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: customer-info-service
    spec:
      containers:
        - name: customer-info-service
          image: ghcr.io/sutarps/customer-info:latest
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
