CREATE TABLE IF NOT EXISTS customer (
    CUSTOMER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    DATE_OF_BIRTH DATE,
    EMAIL VARCHAR(255),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    PHONE VARCHAR(255) );

CREATE TABLE IF NOT EXISTS address (
    ADDRESS_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ADDRESS_TYPE VARCHAR(50),
    CUSTOMER_ID VARCHAR(255),
    HOUSE_NO VARCHAR(255),
    STREET VARCHAR(255),
    CITY VARCHAR(255),
    STATE VARCHAR(255),
    POSTAL_CODE VARCHAR(255),
    COUNTRY VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS CONTACT_DETAILS (
    CONTACT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID BIGINT,
    email VARCHAR(255),
    phone VARCHAR(255),
    CONTACT_TYPE VARCHAR(50)
);
