apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-info-service
  labels:
    app: customer-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-info
  template:
    metadata:
      labels:
        app: customer-info
    spec:
      containers:
        - name: customer-info
          image: ghcr.io/sutarps/customer-info:latest
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8081
            scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            terminationMessagePath: /dev/termination-log
