apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer-info-service
    name: customer-info-service
spec:
  type: NodePort
  selector:
    app: customer-info-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30001