apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: customer-info-service
spec:
  endpoints:
    - intervals: 15s
      port: metrics
      path: /actuator/prometheus
      scheme: http
  selector:
    matchLabels:
      app: customer-info-service